---
sudo: required
language: c
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.atspkg
addons:
  apt:
    packages:
      libgmp3-dev
matrix:
  include:
    - env: TEST=1
      addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-8.4.3
          sources:
            - hvr-ghc
    - env: TEST=1
      addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-8.6.1
          sources:
            - hvr-ghc
    - env: TEST=1
      addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-8.2.2
          sources:
            - hvr-ghc
    - env: TEST=1
      addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-8.0.2
          sources:
            - hvr-ghc
    - env: TEST=1
      addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-7.10.3
          sources:
            - hvr-ghc
    - addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-7.8.4
          sources:
            - hvr-ghc
    - addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-7.6.3
          sources:
            - hvr-ghc
    - addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-7.4.2
          sources:
            - hvr-ghc
    - addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-7.2.2
          sources:
            - hvr-ghc
    - addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-7.0.4
          sources:
            - hvr-ghc
    - env: TEST=1
      os: osx

  allow_failures:
    - os: osx

install:
  - |
    if [ `uname` = "Darwin" ]
    then
      brew install cabal-install
    else
      export PATH=/opt/ghc/bin:$PATH
    fi
  - cabal update
  - curl -sSl https://raw.githubusercontent.com/vmchale/atspkg/master/bash/install.sh | sh -s

script:
  - |
    if [ `uname` = "Linux" ]
    then
      curl -sL https://raw.githubusercontent.com/vmchale/tomlcheck/master/sh/check | sh -s fast-arithmetic/.atsfmt.toml
    fi
  - cd fast-arithmetic
  - atspkg build --pkg-args "./bench.dhall" -vv
  - atspkg test --pkg-args "./bench.dhall" -vv
  - cabal new-build
  - |
    if [ `echo $TEST` = "1" ]
      then
        cabal new-test
    fi
